apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.placeholderSecret.name }}
  name: {{ .Values.placeholderSecret.name }}
  {{- else }}
  name: {{ .Release.Name }}-placeholder-secret
  {{- end }}
  {{- if .Values.placeholderSecret.namespace }}
  namespace: {{ .Values.placeholderSecret.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K